version: '3'
services: 
  todotests:
    image: todotests
    depends_on:
      - "todofront-end"
      - "todoback-end"
    environment:
      - FRONT_HOST=todofront-end
  todofront-end:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - "todoback-end"
    environment:
      - REACT_APP_API_HOST=todoback-end
  todoback-end:
    image: todobackend
    ports:
      - 3001:3001